name = "short"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "short"
database_id = "6efeb455-422c-4cbd-bbaf-b3a1c912be76"
preview_database_id = "DB"
